spring.application.name=employee-service
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/EmployeeManagement
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update

#server.error.include-message=always
#server.error.include-binding-errors=always
#logging.level.org.springframework.web=DEBUG
